# -*- coding: utf-8 -*-
"""Sample Plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ImAavEQl_clgZRLv8IFa0nsnQ4PASMnv
"""

import matplotlib.pyplot as plt

# Data provided
years = [
    "2012-13", "2013-14", "2014-15", "2015-16", "2016-17",
    "2017-18", "2018-19", "2019-20", "2020-21", "2021-22"
]

budget_allocation = [
    797.26, 874.87, 1322.61, 1082.13, 996,
    1393.21, 1575.15, 1600, 2100.42, 1906.14
]

revised_estimates = [
    660, 866.59, 772, 1024.46, 1078.35,
    1393.21, 1381.52, 2000, 1313.4, 1993
]

actual_expenditure = [
    657.88, 809.96, 766.86, 1020.65, 1074.66,
    1229.32, 1297.38, 1989.39, 1304.12, 1748.76
]


plt.figure(figsize=(12, 6))
plt.plot(years, budget_allocation, marker='o', label='Budget Allocation (in crore)')
plt.plot(years, revised_estimates, marker='o', label='Revised Estimates (in crore)')
plt.plot(years, actual_expenditure, marker='o', color='red', label='Actual Expenditure (in crore)')
plt.title('Budget Details for Department of Sports Over the Years', fontsize=18)
plt.xlabel('Year', fontsize=18)
plt.ylabel('Amount in Crore', fontsize=18)
plt.xticks(rotation=45, fontsize=18)
plt.yticks( fontsize=18)
plt.grid(which='both', color='black')
plt.minorticks_on()
plt.grid(which='minor', linestyle=':', linewidth='0.5', color='grey')
plt.legend( fontsize=18)
plt.tight_layout()
plt.savefig('lineplot.jpg', format='jpg')
plt.show()

import matplotlib.pyplot as plt

# Data provided
financial_year = [
    "2014-15", "2015-16", "2016-17", "2017-18", "2018-19",
    "2019-20", "2020-21", "2021-22", "2022-23"
]

num_events_conducted = [
    4640, 3305, 9530, 4788, 5498, 8084, 1954, 481, 672
]

num_participants = [
    371200, 244634, 749307, 558304, 588139, 694730, 156320, 313192, 428158
]

grants_received = [
    12.21, 42.94, 16.71, 10.52, 7.14, 9.78, 1.75, 7.29, 10.56
]

plt.figure(figsize=(12, 6))
plt.tight_layout()
fig, ax1 = plt.subplots(figsize=(10, 7))
plt.title('Relation between no. of events, and no. of participants\n to Grants received Over the Years', fontsize=18)
ax1.scatter(grants_received, num_events_conducted, c='blue', marker='o',s=80, label='Number of Events')

ax1.set_xlabel('Grants Received in Cr', fontsize=18)
ax1.set_ylabel('Number of Events', color='blue', fontsize=18)
ax1.tick_params(axis='both', which='both', labelsize=18, width=1.5)
ax1.minorticks_on()
ax1.grid(which='minor', linestyle=':', linewidth='0.5', color='grey')
ax1.grid(which='major', color='black')
handles1, labels1 = ax1.get_legend_handles_labels()
ax2 = ax1.twinx()
ax2.scatter(grants_received, num_participants, c='green', marker='s',s=80, label='Number of Participants')
ax2.set_ylabel('Number of Participants', color='green', fontsize=18)
ax2.tick_params(axis='both', which='both', labelsize=18, width=1.5)
handles1, labels1 = ax1.get_legend_handles_labels()
handles2, labels2 = ax2.get_legend_handles_labels()
handles = handles1 + handles2
labels = labels1 + labels2
ax1.legend(handles, labels, loc='upper right', fontsize=16)
ax1.legend(handles, labels, loc='upper right', fontsize=16)

plt.subplots_adjust(left=0.15,right=0.8,bottom=0.15)
plt.savefig('scatter_plot.jpg', format='jpg')
plt.show()

import pandas as pd

csv_file = 'CGHS_data.csv'
df = pd.read_csv(csv_file, header=None)
selected_cities = ['PUNE', 'MUMBAI', 'CHENNAI', 'DELHI/NCR', 'BENGALURU', 'KOLKATA']
selected_rows = df[df[1].isin(selected_cities)]
new_df = selected_rows[[1, 5]]
new_df.columns = ['City', 'Num_Doctors']
new_df_copy = new_df.copy()
new_df_copy['Num_Doctors'] = pd.to_numeric(new_df_copy['Num_Doctors'], errors='coerce')
plt.figure(figsize=(10, 6))
plt.boxplot([new_df_copy[new_df['City'] == city]['Num_Doctors'] for city in selected_cities], labels=selected_cities)
plt.title('Doctors in Wellness Centres', fontsize=18)
plt.xlabel('City', fontsize=18)
plt.minorticks_on()
plt.grid(which='minor', linestyle=':', linewidth='0.5',color='grey',axis='y')
plt.grid(which='major', color='black',axis='y')
plt.yticks( fontsize=18)
plt.xticks(rotation=45,fontsize=18)
plt.ylabel('Doctor Count in Wellness Centre', fontsize=18)
plt.tight_layout()
plt.savefig('boxplot.jpg', format='jpg')
plt.show()
